# Generated by Django 6.0.4 on 2026-04-30 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envios', '0003_alter_empleado_estado_alter_encomienda_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EF', 'Efectivo'), ('TA', 'Tarjeta'), ('TR', 'Transferencia'), ('YP', 'Yape'), ('PL', 'Plin')], default='EF', max_length=2)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PE', 'Pendiente'), ('PA', 'Pagado'), ('AN', 'Anulado')], default='PE', max_length=2)),
                ('comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('encomienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='envios.encomienda')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
