# Generated by Django 6.0.4 on 2026-04-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        ('sucursales', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomienda',
            name='alto_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='ancho_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='largo_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='sucursal_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_actuales', to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_destino', to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='sucursal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_origen', to='sucursales.sucursal'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='valor_declarado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
