# Generated by Django 6.0.4 on 2026-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_encomienda_alto_cm_encomienda_ancho_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('ET', 'En Tránsito'), ('ER', 'En Reparto'), ('EN', 'Entregado'), ('CA', 'Cancelado'), ('DE', 'Devuelto')], default='PE', max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_anterior',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('ET', 'En Tránsito'), ('ER', 'En Reparto'), ('EN', 'Entregado'), ('CA', 'Cancelado'), ('DE', 'Devuelto')], max_length=2),
        ),
        migrations.AlterField(
            model_name='historialestado',
            name='estado_nuevo',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('ET', 'En Tránsito'), ('ER', 'En Reparto'), ('EN', 'Entregado'), ('CA', 'Cancelado'), ('DE', 'Devuelto')], max_length=2),
        ),
    ]
