# Generated by Django 6.0.4 on 2026-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0002_alter_ruta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
    ]
