# Generated by Django 6.0.4 on 2026-04-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_doc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de Extranjería'), ('RUC', 'RUC')], default='DNI', max_length=3),
        ),
    ]
